version: "3.9"

services:
  db:
    image: mysql:8.0.36
    container_name: db-sis
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sis
      MYSQL_USER: sis
      MYSQL_PASSWORD: sis
    ports:
      - "3306:3306"
    volumes:
      - $PWD/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    cpu_count: 1
    mem_limit: 1g
    memswap_limit: 1g
    stdin_open: true
    tty: true
